In [1]:
[1,2,3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
[1,2,3]*[4,5,6]

TypeError: can't multiply sequence by non-int of type 'list'

## Numerical Python (Numpy)

In [8]:
import numpy as np

In [9]:
vektor = np.array([1,2,3])
vektor

array([1, 2, 3])

In [11]:
vektor * 3

array([3, 6, 9])

## Math Functions

In [12]:
np.sum(vektor)

6

In [14]:
np.mean(vektor)

2.0

In [16]:
np.std(vektor)

0.816496580927726

In [17]:
np.sin(vektor)

array([0.84147098, 0.90929743, 0.14112001])

## arange, linspace, logspace

In [19]:
np.arange(0,5,2)

array([0, 2, 4])

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.logspace(-3,3,7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

## Random

In [27]:
np.random.rand(3,2) # 3 baris 2 kolom

array([[0.6359216 , 0.17133919],
       [0.91012132, 0.61989227],
       [0.28903513, 0.50830723]])

## Controlled Randomness

In [29]:
state = np.random.RandomState(42)
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])